# Generated by Django 4.2 on 2023-04-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('comentarios', '0001_initial'),
        ('core', '0003_pontoturistico_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontoturistico',
            name='Atracao',
        ),
        migrations.RemoveField(
            model_name='pontoturistico',
            name='Comentario',
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='atracoes',
            field=models.ManyToManyField(related_name='pontos_turisticos', to='atracoes.atracao'),
        ),
        migrations.AddField(
            model_name='pontoturistico',
            name='comentarios',
            field=models.ManyToManyField(related_name='pontos_turisticos', to='comentarios.comentario'),
        ),
    ]
